### ISSUE TITLE
sendmail binary for sending email

### ISSUE THREAD

**Issue by kyrias** [thp/urlwatch#14]
It would be useful if there was an option to use the sendmail binary instead of SMTP.

**Comment by amaury-d** [comment]
Hi, I think too that would be useful

**Comment by muonzoo** [comment]
Can you describe how that would work and on what platforms?

**Comment by kyrias** [comment]
It would just shell out to the sendmail binary, passing the right options, and would work on any UNIX system.

**Comment by thp** [comment]
Wouldn't a local sendmail binary usually also listen on port 25 and accept sent mails this way? Then you could just enter "localhost" as the SMTP host?

**Comment by kyrias** [comment]
`sendmail` is not an SMTP daemon, no.

**Comment by thp** [comment]
This should be easier to implement now with urlwatch 2. Just write a new Reporter subclass (`__kind__ = 'sendmail'` or something) and then make it execute sendmail instead of using SMTP. Alternatively, you might want to just modify the E-Mail reporter and add a configuration option to have it use sendmail instead of SMTP.

**Comment by e-dschungel** [comment]
As a quick hack I did the last suggestion: #60
But I think a cleaner solution would be to modify mailer.py.

**Comment by e-dschungel** [comment]
This issue is fixed by #60 now and can be closed.
