### ISSUE TITLE
Make subfilter parameters configurable

### ISSUE THREAD

**Issue by vmassuchetto** [thp/urlwatch#146]
For any given set of different method parameters, we would have to create a new function to support it. As it's the case with https://github.com/thp/urlwatch/pull/145 for just one simple extra configuration.

Maybe it would be better if we make it configurable, for example:

    filter: html2text:pyhtml2text:body-width=0:protect-links=1:images-with-size=1
    filter: html2text:lynx:list_inline=1:unique_urls=1

Is that a good idea? I would be happy to implement it.

**Comment by thp** [comment]
Yes, although in this case instead of "inventing" a syntax for filter configuration, maybe the `filter` element in the YAML can be either a string (to have the legacy behavior) or a more structured element, that can then have some nicer syntax (i.e. key = filter name, value = a dict of key, value pairs for configuration):

```
filter:
- html2text:
    body-width: 0
    method: pyhtml2text
    protect-links: true
```

So: The filter key has either a string value (then handle as with legacy code), or it has a list value, in which case each list element has as key the filter name and as value the filter configuration (dict). List value so that one can chain different filters (like `,` in the legacy filter string) one after the other.
