### ISSUE TITLE
Cache not migrated

### ISSUE THREAD

**Issue by jwilk** [thp/urlwatch#206]
I tried upgrading from 1.9 to 2.8.
urlwatch successfully migrated the URLs, but not the cache.

I tracked it down to this code in `migration.py`:
```python
    if not os.path.isfile(cache) and os.path.isdir(cache_dir):
```
At this point the cache database file already exists, so this branch is not taken.
Removing `not os.path.isfile(cache) and` fixed it for me, though I'm not sure this is the right way to go.

**Comment by thp** [comment]
From what I can tell, `migrate_cache()` is called unconditionally in `lib/urlwatch/main.py`, but since `.restore()` on the new cache only adds the old entries, and doesn't remove any new ones, plus it renames the old folder later on, it should be fine.

There's also the side effect of running a garbage collection on the cache items, which should be fine, the only "problem" is that if you are using 2.x already, and then create a 1.x cache dir, it will run a GC at first startup, which will remove historic entries of existing feeds, but that shouldn't be too much of a worry.
