### ISSUE TITLE
Implement xpath support

### ISSUE THREAD

**Issue by SingingDwarf** [thp/urlwatch#226]
I see that issues #133 and #155 have been closed, but I cannot see that xpath support has been added.

I see that filters are possible, e.g. filter: element-by-id:something but not how to use xpath.

I want to be able to select e.g.

`//li[@class='contract-wrapper'][2]/div[@class='contract']/div[@class='book book-column']/div/div[@class='price-section']/ol[@class='prices bids']/li[@class='level-0 tick']/span[@class='price']/span[@class='text']/span[@class='formatted-price numeric-value'] `

from the URL [https://smarkets.com/event/867066/politics/uk/uk-party-leaders/may-leader-next-election](https://smarkets.com/event/867066/politics/uk/uk-party-leaders/may-leader-next-election)

**Comment by iiLaurens** [comment]
I would also appreciate a XPath feature. It seems natural to be included in a library as urlwatch, since Google Chrome and other modern browsers so easily allow one to extract a XPath from a website using the inspect functionality. Simply copying such XPath and have urlwatch monitor it truly would be a blessing!

**Comment by kbabioch** [comment]
This would definitely be useful and you could basically copy & paste the filter from your browser. +1 from my point of view ;).

**Comment by kbabioch** [comment]
@vimagick I would suggest to open another issue for this, which will keep it easier to track and find.

**Comment by thp** [comment]
Can anybody who wants to use a specific XPath expression on a specific webpage check if the features from the `ElementTree` library would be sufficient?

https://docs.python.org/3.7/library/xml.etree.elementtree.html#xpath-support

Since it's included in the Python 3 standard library, it'd be possible to add XPath support without adding an external dependency. If that feature doesn't work sufficiently well, we might need to use e.g. `lxml` from https://lxml.de/xpathxslt.html#xpath for those (please requesters also check if the library from above fails if the lxml library would fit the bill).

In general, having a test case (HTML document + XPath expression + expected result) would be super good as a test case and when implementing this feature to see if it works.

**Comment by thp** [comment]
Split off the CSS selectors request to #273 and while doing this I noticed that requests-html also has XPath support: https://html.python-requests.org
