### ISSUE TITLE
Identify jobs not only by URL, but also by filters and/or POST data

### ISSUE THREAD

**Issue by cjohnsonuk** [thp/urlwatch#232]
I want to check for changes in the "article-content"  and the "table of contents" sections on the same web page.  Both sections are in named classes.  This is my config: 

```
kind: url
name: GDPRTableOfContents
url: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/
filter: element-by-class:toc,html2text
---
kind: url
name: Introduction
url: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/
filter: element-by-class:article-content,html2text
---
...etc
```
however when I run urlwatch with this it appears to get confused and reports : 

```
changed: GDPRTableOfContents
--- @	Thu, 10 May 2018 16:26:04 +0100
+++ @	Thu, 10 May 2018 16:27:15 +0100
@@ -1,4 +0,0 @@
-            Introduction
-The Guide to the GDPR explains the provisions of the GDPR to help organisations comply with its requirements. It is for those who have day-to-day responsibility for data protection.
-This is a living document and we are working to expand it in key areas. It includes links to relevant sections of the GDPR itself, to other ICO guidance and to guidance produced by the EU’s Article 29 Working Party. The Working Party includes representatives of the data protection authorities from each EU member state, and the ICO is the UK’s representative.
-Alongside the Guide to the GDPR, we have produced a number of tools to help organisations to prepare for the GDPR:
________________________________________
urlwatch 2.9, Copyright 2008-2018 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 38 URLs in 3 seconds 
```
when that text still exists in the page. My first check on page in the "table of contents" section is to check that no new pages have been added to the website.  The second check of that page is to check that the introduction text itself has not been changed.  There are then about 40 other checks on the other pages linked from the table of contents.  Does the cache use the name as well as the URL to uniquely identify each page check?

**Comment by cjohnsonuk** [comment]
I've worked out you can append a # to the URL of the page the second time you want to use it to make the URL unique eg

```kind: url
name: DevTest
url: https://www.domain.com/
filter: element-by-id:pagelist,html2text
---
#same page different ID added # to end of path to make it unique
kind: url
name: DevTest2
url: https://www.domain.com/#
filter: element-by-id:header,html2text
---
```
works to allow you to use one page multiple times.

**Comment by thp** [comment]
Yeah the anchor-link workaround works there. I wonder if it would make sense to allow a list of filters and urlwatch would take care of running all filters and then appending the results? Something like:

```
name: DevTest
url: https://www.example.com/
filter:
   - element-by-id:pagelist,html2text
   - element-by-id:header,html2text
```

This could probably be implemented without breaking existing config files (if it's a list, treat each filter separately, otherwise just apply the single filter).

**Comment by sbraz** [comment]
I'm also using the anchor hack because I track the same page with different post data payloads. 

Ideally, I would  like to have something like a `display_url` attribute that would be unique but would not be the same as the actual URL that I watch:
```yaml
url: https://someapi.com/api
display_url: https://some-site-with-ajax.com/identifier
data:
  id: someidentifier
```

**Comment by gaia** [comment]
https://github.com/thp/urlwatch/issues/232#issuecomment-390005477 seems like the most elegant solution

**Comment by sbraz** [comment]
@gaia It won't work if I want to pass different POST DATA for the same URL.

**Comment by gaia** [comment]
@sbraz 

Different post data should yield different results and the anchor hack should not be needed. The fact that post data itself is present should be enough to indicate to URLwatch that the response will be different because of differing post data (and thus URLwatch should no reuse the response).

On the other hand, using the same URL indicates that the same results (at least at a specific given point in time) are expected. Only (in some use cases) they need to be filtered differently, so URLwatch should not make two requests in this case.

These are two different use cases requiring two different solutions.

**Comment by thp** [comment]
Let's go with the anchor hack for now.
