### ISSUE TITLE
Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by svenbluege** [thp/urlwatch#297]
I use the standard check in my configuration for the urlwatch website. Since a couple of days, I get an error message like the one below. Other URLs continue working fine. Has anyone an idea how to solve this? I'm happy to provide any information you might need. I use the latest version 2.15 but had this issue with 2.14 as well. 

```
kind: url
name: urlwatch webpage
url: https://thp.io/2008/urlwatch/
filter: html2text,grep:Current.*version,strip

```

```
===========================================================================
01. ERROR: urlwatch webpage
===========================================================================

---------------------------------------------------------------------------
ERROR: urlwatch webpage (https://thp.io/2008/urlwatch/)
---------------------------------------------------------------------------
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
---------------------------------------------------------------------------

```

**Comment by svenbluege** [comment]
While having no clue what I'm doing, I update the packages urllib3 and requests to the latest version. It did not change the behavior. 

```
requests (2.20.0)
urllib3 (1.24)
```

**Comment by cfbao** [comment]
The issue is related to the etag value. 
The current etag of https://thp.io/2008/urlwatch/ consists of pure digits, which seems to be causing some parsing error.
It's `"3621764564"` (with literal quotes) as returned by `requests`. But if you pass `"3621764564"` to the request header, this error occurs. You have to set it to `3621764564` (str type, but without literal quotes).

I don't know where the source of this error is.

You can workaround it by adding `ignore_cached: true` to your url config, so etag value isn't used at all.

**Comment by svenbluege** [comment]
The workaround worked well. Thank you very much! I'll close this issue.

**Comment by thp** [comment]
This might also be a server misconfiguration..
