### ISSUE TITLE
Cache database redesign

### ISSUE THREAD

**Issue by cfbao** [thp/urlwatch#347]
I've been thinking about tackling the following issues:
* Support job specific check intervals #148, #171
* Find the latest entry of a job accurately #335
* Avoid cache entries duplication #326
* Export site change/version history #53, #170

I believe a redesign of the cache database can help with all these issues.

#### General idea
* Use one table to store snapshots data, where each row corresponds to a distinct snapshot of retrieved data. Rows are immutable.
* Use another table to store job info, where each row corresponds to a different job, together with its last run state info. Rows are mutable.

Currently, the `CacheEntry` table mixes both snapshot info and last run state info. This makes it inflexible to extend and prone to duplication.

#### Tentative details
* Add a new table called `LastRunState`, with columns `guid`, `name`, `location`, `last_checked_time`, `last_snapshot_id`, `tries`, `etag`...
* Deprecate the `tries` and `etag` columns of `the CacheEntry` table.

Then there's the tricky issue of migration... which I'm not sure how best to do it yet.

**Comment by thp** [comment]
Sounds good! As for the migration, we probably have to leave the old database code in, so that it can migrate e.g. added fields in the old format still and then migrating from old to new always has a fixed structure (no missing fields/columns).

In previous projects, having the new database/cache have a new file name and migrating the old file (and renaming it by appending something like "-migrated", NOT deleting it, so in case migration fails, the user can recover the old state) turned out to be the safest approach.

**Comment by thp** [comment]
Let's continue the discussion in #360, closing this for now.
