### ISSUE TITLE
get notified of new facebook events

### ISSUE THREAD

**Issue by fabienmorin** [thp/urlwatch#407]
I don't have any FB account but I'm trying to get informed of some public pages. Especially, I'd like to get notified when there is a new event.

For this, I tried the following config :
kind: url
name: Facebook test
url: https://www.facebook.com/pg/FacebookPageIWantToFollow/events/?ref=page_internal
filter:
    - element-by-id: upcoming_events_card
    - html2text: pyhtml2text

but it doesn't work as expected, I never get notified, even when a new event is added whereas it works for other sites than FB. Any idea how I could achieve that ?

**Comment by thp** [comment]
Does the page require to be logged in? What if you add the cookies from your browser so the settings so that it can use your logged-in session?

**Comment by fabienmorin** [comment]
no, as I said before, I have no FB account but I'd liked to watch public pages to get notified in case of new event (which is possible to do by hand without account)

**Comment by mborsetti** [comment]
Have you tried debugging using `--test filter` as per docs (https://urlwatch.readthedocs.io/en/latest/filters.html)?

Also, when I go to that page from an Incognito browser, that page looks like below, and I presume it rarely changes (so there's very little for urlwatch to pick up).  If that's not what you're trying to monitor, then you're using an incorrect URL.

![image](https://user-images.githubusercontent.com/26698111/87505943-be696f00-c69c-11ea-9658-2ae6049043cf.png)

**Comment by thp** [comment]
> no, as I said before, I have no FB account but I'd liked to watch public pages to get notified in case of new event (which is possible to do by hand without account)

I have given it a try and it seems Facebook loads data dynamically, which is why you don't see the events. As a workaround, I tried the following and this worked for me (you can test with `--test-filter`, obviously you need to replace `FacebookPageIWantToFollow` with a real Facebook page that has events):

```
navigate: https://m.facebook.com/FacebookPageIWantToFollow/pages/permalink/?view_type=tab_events
filter:
  - css: div._5zma
  - html2text
```

Some things to note:

1. Use `m.facebook.com`, which is a simpler page format
2. Use `navigate` to use [requests-HTML](https://requests.readthedocs.io/projects/requests-html/en/latest/) for executing JavaScript (this requires `python3 -m pip install requests_html`)
3. On the mobile page, for the "Event" click on "See All" (this is `/pages/permalink/?view_type=tab_events`)
4. On the browser, right-click on the event list and use "Inspect Element" (or similar, depending on browser -- might need developer tools enabled) to find out the CSS filter class `_5zma`

The regex-based `html2text` (default is `re`, i.e. strip tags using regular expressions) worked fine for me, but you can of course try others for nicer output.

Let me know if this works for you and I can add it to the documentation as a "recipe".

**Comment by fabienmorin** [comment]
it seems to work as expected, thanks for the help ! You can add this as a new recipe

**Comment by thp** [comment]
btw, i've updated the docs to work with just the static mobile page: https://github.com/thp/urlwatch/commit/d48716c854ddcafa80c74f52d2f6c2116a1ee2fd

**Comment by mborsetti** [comment]
See #519 to be notified only of new (added) content.

**Comment by mborsetti** [comment]
See https://github.com/mborsetti/urlwatch to be notified only of new (added) content.
