### ISSUE TITLE
Grep filter assist

### ISSUE THREAD

**Issue by strauhmanis** [thp/urlwatch#419]
Hi!
This is a request for assist with grep filter, if you could, please.

The goal is to check/store the price, as follows:

`url: "https://apps.apple.com/us/app/plantsnap-plant-identification/id1234702272"`
`filter: grep:(@type":"Offer"\054"price":)\d+[\054.]?\d+`

Viewing the `cache.db` after urlwatch processed the page, I see that the the whole line, of which the above section `@type":"Offer","price":9.99` is part of, is being stored. And the line is some 7000+ characters.

Please advise how do I make urlwatch to store only the `@type":"Offer","price":9.99` part.

Many thanks in advance!

**Comment by mcint** [comment]
Not currently possible that way.

Maybe use the RegexFilter with `(.*)(your-pattern)(.*)` and return capture group 2. It might possible, but it will have terrible performance. Although, it looks like it can only replace with a predetermined fixed pattern :(.

If this shelled out to grep, `-o` but [current behavior](https://github.com/thp/urlwatch/blob/67b7146e20dc2c4fae8650fcd726ef46f0f9b737/lib/urlwatch/filters.py#L202-L212) is `line ... if re.search(subfilter, line)`.

You could submit a patch. I do wish urlwatch played nicer with existing tools, instead of half implementing features.

**Comment by thp** [comment]
In the master branch (not yet in a release) there's now the `shellpipe` filter which you can use to pipe the content through a shell command, so you can use the `grep` command line utility with any parameters you want.

This is documented with examples here (the first example is probably the use case you want):
https://urlwatch.readthedocs.io/en/latest/filters.html#using-a-shell-script-as-a-filter

**Comment by thp** [comment]
This is now in urlwatch 2.19.
