### ISSUE TITLE
Please set $VISUAL or $EDITOR.

### ISSUE THREAD

**Issue by AltaCursor** [thp/urlwatch#438]
when I try to urlwatch --edit, it asks me to set $VISUAL or $EDITOR, but I already set it using the export command, if I'm not mistaken? 

Any suggestions much appreciated.
 
<img width="487" alt="Screenshot 2019-12-09 at 23 12 50" src="https://user-images.githubusercontent.com/58709948/70477768-e165ec00-1ad9-11ea-88c7-d802e5cbd6fe.png">

**Comment by carlzoo** [comment]
This does not appear to be a urlwatch issue. Sudo can't access the environment variable you set as a non-sudo user.

Perhaps what you want is:
`sudo -E bash -c 'urlwatch --edit'` if you intend on running urlwatch as sudo user

or

`urlwatch --edit` just run urlwatch as non-sudo user

**Comment by thp** [comment]
Why do you need to run `urlwatch` as root? Try not using `sudo`. If you have good reasons for running urlwatch as root, first switch to a root shell using e.g. `sudo -i` and THEN set the environment variable there.

Note that nothing in urlwatch requires running as root, so running as root increases the attack surface of your machine, because now all the code in urlwatch that normally runs as normal user now runs as root.

**Comment by kmbecker13** [comment]
I have this same problem when running on Windows (without sudo)

`urlwatch --edit` returns "Please set $VISUAL or $EDITOR"

**Comment by SHU-red** [comment]
Try
export EDITOR=nano

No ""

**Comment by kmbecker13** [comment]
Thanks for the quick response!  I think you need "SET" instead of "EXPORT" on Windows from my recent googling, but either way that doesn't seem to have much effect.  

I've also tried other variations of that command and don't see any errors when i run them (it doesn't return anything) but the `urlwatch --edit` still fails afterwards.

**Comment by Jorman** [comment]
Can be a venv setup?
I just installed urlwatch in virtual env and I got this error
I temporarily resolved with
export EDITOR="/usr/bin/nano"
export VISUAL ="/usr/bin/nano"

I'll put vars inside environmet or some
