### ISSUE TITLE
Repeated messages for 502

### ISSUE THREAD

**Issue by codaamok** [thp/urlwatch#489]
Hello

I am monitoring some URLs where currently it's producing a 502 Server Error because indeed those webpages are offline due to server error (those URLs are my applications).

If I run `urlwatch` over and over, it's repeatedly identifying these as new changes every time i.e. sending me a push notification that the same URLs have the same 502 server error message for each call to `urlwatch`. I thought it would have recognised the first time it saw 502 server error, then the next time ignored it because nothing changed? So in other words, only notifying me once that there is a 502 server error on these pages.

Cheers

**Comment by cfbao** [comment]
This is expected default behaviour. On error it always notifies.
You can use the [`max_tries` optional key](https://urlwatch.readthedocs.io/en/latest/jobs.html#optional-keys-for-all-job-types) so that it only notifies an error after a set number of failed attempts.
Alternatively, ignore certain errors altogether with [`ignore_http_error_codes`](https://urlwatch.readthedocs.io/en/latest/advanced.html#ignoring-connection-errors).

**Comment by codaamok** [comment]
thank you
