### ISSUE TITLE
pip uninstall urlwatch deletes /usr/share/

### ISSUE THREAD

**Issue by Eriner** [thp/urlwatch#52]
This may have been a fluke, but in removing urlwatch with pip (to use Arch's python-urlwatch instead), pip deleted my whole `/usr/share/`. I was able to recover, but I don't want that to happen to anyone else. I don't have time to dig into exactly why it happened, but based on a conversation in another thread, there seems to be some issue with where/how urlwatch installs (and uninstalls).

**Comment by brbsix** [comment]
Wow that's pretty crazy. Is there any reason in particular that you were running pip with sudo/root privileges? Assuming you aren't working in a virtualenv or something, you'd generally you'd only want to install with the `--user` flag which doesn't require elevated privileges.

**Comment by Eriner** [comment]
It was in a virtual machine that I was playing with some stuff in; everything was running as root. The deletion of `/usr/share/` wasn't a big deal, I didn't even have to restore from a snapshot; a few lines in bash and I was good-to-go again. Just wanted to make the issue in case anyone else ran into this (or if this is a bug with urlwatch that can be avoided).

**Comment by thp** [comment]
Pushed a change that might improve the situation. Previously, the `setup.py` script had an invisible assumption coded in that you run the setup.py script from the source directory. Now, it should work correctly even when running from somewhere else. Still unsure why it happened, but it could be that if you run `setup.py` with the current working directory being `/usr` (because it scans `share` in the current directory to see which files are to be installed, which works great when running from the source tree).

**Comment by chid** [comment]
Could you please push v2.2 to pypi? This bug still occurs on that version.

**Comment by thp** [comment]
Done.
