### ISSUE TITLE
deprecation warning for html2text

### ISSUE THREAD

**Issue by neiaberau** [thp/urlwatch#529]
Hi,
I just tried to upgrade to version 2.19 and I unfortunately now I get many warnings such as, 
    filters WARNING: String-based filter definitions (html2text) are deprecated, please convert to dict-style
(which is ok, I guess, as it is mentioned in the release notes)
 
I tried to find out in the manual, what I need to change, I search for "dict-style" in the manual, but did not find anything,  
but probably I do not look for the right thing, What do I need to change?

my current setup is really simple I just use html2text, nothing more, such as::

kind: url
name: test
url: https://wwww.aaa.com
filter: html2text

I am not a python programer, so maybe this is something that might be obvious for others.

**Comment by thp** [comment]
Good point, it should be more clearly documented, and if it's just a single filter, it might not be obvious what the benefits are.

I've now documented this in 09ef6287180c387f0b842ef2e5cfe112b350bcc5 and the warning should now contain a link to the documentation page on readthedocs (https://urlwatch.readthedocs.io/en/latest/deprecated.html) which should explain why this was deprecated with an example of old/new and also your case specifically (because for single-value items it might not be clear).
