### ISSUE TITLE
element-by-class: specify wildcard

### ISSUE THREAD

**Issue by notDavid** [thp/urlwatch#636]
Hi there,

Is it possible to specify a wildcard in the class name, via regex or something?
A page i want to monitor appends/generates random characters to the end of the class name.

How would i match all of these for example:

contentWrap--qVat7asG
contentWrap--wSlxapCk
contentWrap--JV0HGsqD
etc.

I would imagine something like this, but it doesn't work and i could not find anything in the docs;
```
filter:
  - element-by-class: contentWrap*
  - html2text
```

Thank you!

**Comment by c0deing** [comment]
Hey,

i dont know a way to do this right away from the urls.yaml file as you are trying to accomplish but you could use:

    filter: 
       - shellpipe: python3 /pathToYourScript

And in your script you could use BeautifulSoup like this:

    from bs4 import BeautifulSoup
    import os, sys, re

    htmlinput = sys.stdin.read()
    soup = BeautifulSoup(htmlinput, 'lxml')
    
    #search for "div" elements with the according class
    matches = soup.findAll("div", {"class" : re.compile('contentWrap--*')})
    
    #printing out the first found match
    print(matches[1])

doing this should print the results in urlwatch or the reporter you are using

keep in mind that you need to install BeautifulSoup first (as described [here](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-beautiful-soup))

Also i encourage you to check out BeautifulSoup more in depth as there are many useful functions that could help you getting the information that you are trying to filter/scrape from the webpage

I hope this helps

feel free to ask if you have some more questions, otherwise you could mark this issue as "closed"

**Comment by notDavid** [comment]
Hi @c0deing 

thanks so much for the detailed explanation! I will check it out right away... (and maybe report back if it doesn't work :-)

Have a nice day,
David.
