### ISSUE TITLE
Running a subset of jobs does not work?

### ISSUE THREAD

**Issue by Filip-K** [thp/urlwatch#661]
Attempting to run the `urlwatch 2 4 7` example from the docs gives `urlwatch: error: unrecognized arguments: 2 4 7` on my urlwatch 2.23. Am I doing something wrong (I do have more than 7 jobs)?

**Comment by proxseas** [comment]
I ran into the same issue.

**Comment by thp** [comment]
I have now enabled some older version tags on readthedocs, this isn't perfect of course (a "since version x.y.z" would be best, but alas, we don't know the version yet when the docs are written in development, and "since version 2.25" would be even more confusing if 2.25 hasn't even been released yet):

https://urlwatch.readthedocs.io/en/2.23/
