### ISSUE TITLE
watch binary files

### ISSUE THREAD

**Issue by e-dschungel** [thp/urlwatch#68]
It would be nice if urlwatch would be able to watch changes in binary files like images or PDFs by their hashed content.

**Comment by thp** [comment]
You can do this for local files by just piping it into `sha1sum` or a similar tool or even `hexdump` if you want to see which bytes change. For things like PDF you can also pipe it through a tool that converts the PDF to text, so you can even see text changes.

**Comment by e-dschungel** [comment]
Is there a way for remote files, too? This would my use case.

**Comment by brbsix** [comment]
This is probably a bad idea for a number of reasons, but perhaps something like the following would work for your particular use case?

    curl -Is URL | awk '$1 ~ /Last-Modified:/ {sub(".*: ", ""); print}'

**Comment by thp** [comment]
The next version will have two additional filters that will help here:

 * `sha1sum` - Takes the retrieved content and returns the sha1sum as hexdigest
 * `hexdump` - Takes the retrieve content and returns a hexdump-like representation

The hexdump output doesn't include file offsets, as otherwise the diffs will be quite large.

**Comment by e-dschungel** [comment]
@thp Thanks, sha1sum solves my usecase perfectly.

**Comment by thp** [comment]
Note that this will still download the file every time fully when watched. A more efficient solution would be to only do a HEAD request and then use either ETag or Last-Modified as suggested by @brbsix, but we do not have that feature (getting HTTP headers) yet. We do already support specifying the HTTP method, so maybe if it's HEAD, the content should be the raw headers, since the body will always be empty, anyway.
