### ISSUE TITLE
Show error when filters don't match anything

### ISSUE THREAD

**Issue by knutwannheden** [thp/urlwatch#682]
I would like to use urlwatch to monitor a rather large set of pages. Many of these pages are expected to change every now and then (without notice) so that the urlwatch filters need to be adapted to the new page. I was therefore hoping to see an error when a filter like for example `element-by-tag` doesn't match anything anymore.

**Comment by mborsetti** [comment]
Not sure if this would help you, but the [webchanges](https://pypi.org/project/webchanges/) fork (optimized for HTML) has an --error [--error](https://webchanges.readthedocs.io/en/stable/cli.html#show-errors-and-no-data-jobs) command line argument you can run periodically which highlights any jobs that have no content after filters are applied.

In any case if a job used to match "ABC" but if after a change in the source website nothing is being matched anymore, you will get a change notification with the deletion of "ABC".  The rationale for the ``--error`` command line argument was to be able to do periodic checks in case such a change was being missed, but probably more can be done.

**Comment by thp** [comment]
You can use `--test-filter JOB` to see if the filter still works. When creating the entry and testing the filter, usually it will have some output. If that output then changes to the empty string, because the webpage changed, you will anyway get a notification.

An empty match doesn't necessarily mean the job "fails" (urlwatch can also be used to "wait" for an element to (re-)appear).
