### ISSUE TITLE
urlwatch in github actions?

### ISSUE THREAD

**Issue by Hans-Maulwurf** [thp/urlwatch#769]
Hello,

is it possible to run urlwatch within github/github actions like website-stalker https://github.com/EdJoPaTo/website-stalker ? couldn't find any comments to this use, but this would be awesome. appreciate any hints :)

**Comment by Hans-Maulwurf** [comment]
nobody?

**Comment by thp** [comment]
Pretty sure that would be [against the intent / terms of use / acceptable use policy](https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions) for Github Actions. We wouldn't want Github Actions to be more restricted for build projects because of crypto miners, and people who run non-build payloads on Github Actions because they are too cheap to host/rent their own infra.

There's other ways to get free or cheap compute, I can think of 3 right off the bat:

1. Just get a cheap VPS and run your stuff there
2. Register for one of the many free shell accounts that allow running cron jobs
3. Buy a Raspberry Pi Zero (2) W and run it at home at low power usage

For a cheap VPS, I may recommend Digital Ocean, which I'm using myself. They call VPSs "Droplets" there, and the most basic one for $4/month is plenty for urlwatch usage. Here's a referral link that you can use to get $200 in digital ocean credit (useful for 60 days, so you should be able to trial it for free for 2 months): https://m.do.co/c/acd11a762758 (it's my personalized referral link, once you spend $25 on the service, I get $25 credit on my account, so a great way to support the urlwatch project in any case -- anyone reading this is of course free to use the link :))

For a free shell account, use freeshell.de, you just need to send in a paper postcard to activate your free account. Or just google "free unix shell account". Be sure to read their acceptable use policy, though!

For a Raspberry Pi Zero (or Pi Zero W / Pi Zero 2 W to use Wifi), check [rpilocator](https://rpilocator.com) or your local electronics shop (any other Linux-based SBC will work just as well, the Pi Zero just happens to be really cheap, really small and really low power usage). If you already have electricity and an internet connection at home, that might be the cheapest option while still giving full control.

Closing as something we do not want to do or support.
