### ISSUE TITLE
Using Remote urls.yaml File

### ISSUE THREAD

**Issue by goodgrowth** [thp/urlwatch#84]
I'm having an issue with setting the target variable for my urls.yaml file. 

I was trying to point it to my web server so that I could modify the urls I want to use even when I'm not on my home machine. I keep getting an error everytime I set the urls_yaml variable on line 51.

```
SyntaxError: invalid syntax
  File "/Users/xxxPython/urlwatch-2.2/urlwatch", line 51
    urls_yaml = 'http://pathtourl.com/urls.yaml')
                                                ^
```

Is this possible?

**Comment by thp** [comment]
The syntax error you get is the closing `)` - it shouldn't be there. That said, it still won't work, as urlwatch expects that to be a local filename (you could patch the code to accept URLs, but that's a bit more involved).

Note that also since urlwatch can also run shell jobs, this means that when somebody controls your web server (or can somehow modify the request/response), they can run shell scripts on your home machine this way or direct your urlwatch client to do HTTP requests to any server. For this reason, this shouldn't go into urlwatch proper as a feature.

If you really want to do this, and are aware of the security implications (arbitrary code execution on your home server once your web server or the connection to it is hijacked), set up another cron job that just uses `wget` or `curl` to download the remote file to the local `urls.yaml`, so you don't need to modify urlwatch at all, and you can even have a different schedule for when to update `urls.yaml`.

And since you already have a web server, why not run urlwatch on there and send the results to you via e-mail or something?

**Comment by goodgrowth** [comment]
Hi Thomas,

Thank you for the quick reply and thorough explanation. You're definitely right. I was not thinking about the implications of someone running shell commands if they were to gain access to my server. I am going to not worry about that integration since it could be more damaging than it's worth.
